services:
  block09-db:
    image: block09-db
    container_name: block09-db
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - ./db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    networks:
      - app-network
  block09-app:
    depends_on:
      - block09-db
    image: block09-app
    container_name: block09-app
    ports:
      - "${PORT}:3000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_HOST=block09-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
